"""Self-check: verifies the TOOL, not a workbook."""
from __future__ import annotations

import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

MODULE_MAP = os.path.join(HERE, "README.md")

DOCS = {
    "CLAUDE.md": "agent landing: what, run, check, laws, where knowledge lives",
    "AGENTS.md": "the same landing for other agents (symlink to CLAUDE.md)",
    "README.md": "for people: what it is, install, limits, licence",
    "mcp/twkit/README.md": "module map, check channels, frame, editing the owner's workbook",
    "tools/README.md": "dev scripts",
    "tests/README.md": "test suites and conventions",
    "docs/DESIGN_KB.md": "craft: how to build clear, insightful dashboards",
    "docs/STYLE_GUIDE.md": "measured house style: numbers, not opinions",
    "docs/NAMING_RULES.md": "naming and data pane folders (checked by R35)",
    "docs/REPORT_DOC_STANDARD.md": "standard for dashboard descriptions: facts only",
    "docs/FORMAT_NOTES.md": "the XML dialect (generated by tools/xsd_notes.py)",
    "docs/TABLEAU_APP_NOTES.md": "facts extracted from installed Tableau",
}

GENERATED_DOCS = {"docs/FORMAT_NOTES.md"}
ALIASES = {"AGENTS.md"}


def module_map() -> dict:
    """{module: role} from the table in mcp/twkit/README.md."""
    rows = re.findall(r"^\|\s*`([\w/]+)\.py`\s*\|\s*([^|]+?)\s*\|", _read(MODULE_MAP), re.M)
    return {m: role for m, role in rows}


def _read(path: str) -> str:
    try:
        return open(path, encoding="utf-8").read()
    except OSError:
        return ""


def channels_wired() -> list:
    """Every channel in the module map must be called from preflight."""
    src = _read(os.path.join(HERE, "preflight.py"))
    if not src:
        return ["preflight.py is unreadable; channel wiring not checked"]
    bad = []
    for mod, role in module_map().items():
        if role.startswith("channel") and mod not in src:
            bad.append(f"{role} ({mod}.py) is not called from preflight")
    return bad


def modules_classified() -> list:
    """Every module is described in the module map, and the map lists no ghosts."""
    known = set(module_map())
    found = {os.path.splitext(f)[0] for f in os.listdir(HERE)
             if f.endswith(".py") and f != "__init__.py"}
    server = os.path.join(HERE, "server")
    if os.path.isdir(server):
        found |= {"server/" + os.path.splitext(f)[0] for f in os.listdir(server)
                  if f.endswith(".py") and f != "__init__.py"}
    bad = [f"module {m}.py is not in the module map (mcp/twkit/README.md)" for m in sorted(found - known)]
    bad += [f"module map lists {m}.py, which does not exist" for m in sorted(known - found)]
    tools = os.path.join(ROOT, "tools")
    listed = _read(os.path.join(tools, "README.md"))
    for f in sorted(os.listdir(tools)) if os.path.isdir(tools) else ():
        if f.endswith(".py") and f"`{f}`" not in listed:
            bad.append(f"tools/{f} is not described in tools/README.md")
    return bad


def dead_modules() -> list:
    """A module nobody imports is dead code."""
    mods = {os.path.splitext(f)[0] for f in os.listdir(HERE)
            if f.endswith(".py") and f != "__init__.py"}
    body = ""
    for sub in ("mcp", "tests", "dashboards", "tools"):
        d = os.path.join(ROOT, sub)
        for cur, _dirs, files in os.walk(d):
            if "__pycache__" in cur:
                continue
            for f in files:
                if f.endswith(".py"):
                    body += _read(os.path.join(cur, f))
    dead = []
    for m in sorted(mods):
        if m in ("selfcheck",):
            continue
        uses = len(re.findall(rf"\b(?:twkit\.{m}|from \.{m}|from twkit import [^\n]*\b{m}\b|"
                              rf"import {m}\b)", body))
        if uses <= 1:
            dead.append(f"module {m}.py is imported by nobody: wire it in or delete it")
    return dead


def docs_consistent() -> tuple:
    """Knowledge duplicated across documents, and dangling references."""
    bad, gaps = [], []
    heads: dict = {}
    for doc in DOCS:
        if doc in ALIASES:
            continue
        path = os.path.join(ROOT, doc)
        if not os.path.exists(path):
            bad.append(f"document {doc} is declared in selfcheck but missing")
            continue
        for h in re.findall(r"^## +(.+)$", _read(path), re.M):
            key = re.sub(r"^\d+\.\s*", "", h).strip().lower()
            heads.setdefault(key, []).append(doc)
    keys = sorted(heads, key=len)
    for i, short in enumerate(keys):
        if len(short) < 12:
            continue
        for long in keys[i:]:
            if short == long or short not in long:
                continue
            docs = sorted(set(heads[short]) | set(heads[long]))
            if len(docs) > 1 and not set(docs) & GENERATED_DOCS:
                bad.append(f"section '{short[:44]}' is repeated in {', '.join(docs)}; "
                           f"keep it in one and link from the other")
    for key, docs in heads.items():
        if len(set(docs)) > 1 and not set(docs) & GENERATED_DOCS:
            bad.append(f"section '{key[:48]}' exists in {', '.join(sorted(set(docs)))}; "
                       f"keep it in one and link from the other")

    top = {f for f in os.listdir(ROOT) if f.endswith(".md")}
    top |= {f"docs/{f}" for f in os.listdir(os.path.join(ROOT, "docs")) if f.endswith(".md")} \
        if os.path.isdir(os.path.join(ROOT, "docs")) else set()
    for f in sorted(top - set(DOCS)):
        bad.append(f"document {f} is not declared in selfcheck")
    for a in ALIASES:
        if os.path.realpath(os.path.join(ROOT, a)) != os.path.realpath(os.path.join(ROOT, "CLAUDE.md")):
            bad.append(f"{a} must be a link to CLAUDE.md, not a second copy")

    claude = _read(os.path.join(ROOT, "CLAUDE.md"))
    past = ("deleted", "removed", "no longer")
    for line in claude.splitlines():
        if any(w in line.lower() for w in past):
            continue
        for ref in re.findall(r"`([\w./_-]+\.(?:py|md|yml))`", line):
            cand = [os.path.join(ROOT, ref), os.path.join(ROOT, "mcp", ref),
                    os.path.join(ROOT, "docs", ref)]
            if not any(os.path.exists(c) for c in cand):
                gaps.append(f"CLAUDE.md references `{ref}`, which does not exist")
    return bad, gaps


def selfcheck() -> dict:
    """All toolkit invariants at once."""
    findings: list = []
    gaps: list = []

    findings += channels_wired()
    findings += modules_classified()
    findings += dead_modules()
    bad, g = docs_consistent()
    findings += bad
    gaps += g

    gaps.append("corpus calibration and check behaviour are covered by tests/")
    return {
        "verdict": ("consistent" if not findings else
                    f"invariant violations: {len(findings)}"),
        "findings": findings,
        "not_checked": gaps,
    }


def format_report(r: dict) -> str:
    lines = [f"Toolkit self-check: {r['verdict']}"]
    for f in r.get("findings") or []:
        lines.append(f"  ✗ {f}")
    for g in r.get("not_checked") or []:
        lines.append(f"  ? {g}")
    return "\n".join(lines)
